image: haskell:latest

before_script:
  - apt-get update && apt-get install xz-utils make
  - export STACK_ROOT=`pwd`/.stack
  # Save build cache even when it fails.
  - stack build || true

cache:
  paths:
    - _cache
    - .stack

build:
  script:
    - stack exec hakyll build
  artifacts:
    paths:
      - _site
  except:
    - master

pages:
  script:
    - stack exec hakyll build
  artifacts:
    paths:
      - _site
  only:
    - master
